apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-name
  labels:
    app: acr-app01
spec:
  replicas: 2
  selector:
    matchLabels: 
     app: acr-app01
  template:
    metadata:
      labels:
        app: acr-app01
    spec:
      containers:
      - name: custom2aksnginxapp2
        image: acradedemo2.azurecr.io/custom2aksnginxapp2
        ports:
          - containerPort: 80
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: acr-app01-loadbalancer-service
  labels:
    app: acr-app01
spec: 
  selector:
    app: acr-app01
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
